n7           = n7-dfs-batch
n7-dfs       = --n=7 --precalc-alg=dfs --solve-alg=dfs
n7-bfs       = --n=7 --precalc-alg=dfs --solve-alg=bfs
n7-dfs-batch = --n=7 --precalc-alg=dfs --solve-alg=dfs-batch
n7-dfs-swarm = --n=7 --precalc-alg=dfs-swarm --solve-alg=dfs-swarm --dfs-swarm-max-groups=5
             
n8           = n8-dfs-swarm
n8-dfs-batch = --n=8 --save-files --precalc-alg=dfs --solve-alg=dfs-batch --dfs-batch-size=10000 --dfs-batch-max-cache=250000000 --max-loop-123=40 --max-loop-45=20
n8-dfs-disk  = --n=8 --save-files --precalc-alg=dfs --solve-alg=dfs-disk --dfs-disk-block-size=10000000 --dfs-disk-batch-size=5000000 --dfs-disk-seen-size=20000000 --max-loop-123=40 --max-loop-45=20
n8-dfs-swarm = --n=8 --save-files --precalc-alg=dfs-swarm --solve-alg=dfs-swarm --dfs-swarm-max-groups=10 --dfs-batch-size=10000 --dfs-batch-max-cache=1000000000 --max-loop-123=40 --max-loop-45=20

n9-precalc7  = --n=9 --save-files --checkpoint-shapes=1/4;1/5;5/5;5/5,5/5;1/6;1/7 --max-precalc-shape=1/7 --precalc-alg=dfs --solve-alg=none                                                                             
n9-precalc9  = --n=9 --save-files --checkpoint-shapes=1/6;1/7;1/9 --precalc-alg=dfs-batch --dfs-batch-size=10000 --dfs-batch-max-cache=8000000000 --solve-alg=none                                                         
n9-solve     = --n=9 --save-files --checkpoint-shapes=1/9 --precalc-alg=none --solve-alg=dfs-disk --dfs-disk-block-size=100000000 --dfs-disk-batch-size=10000000 --dfs-disk-seen-size=$SEEN_SIZE --max-loop-123=80 --max-loop-45=60
